services:
  shopgrid-products-postgres:
    container_name: shopgrid-products-postgres
    image: postgres:18-alpine
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=mike
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=products_db
    volumes:
      - shopgrid-products-postgres-volume:/var/lib/postgresql/data
    networks:
      - shopgrid-network

  products-service:
    build:
      context: .
      dockerfile: products-service/Dockerfile
    container_name: products-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - shopgrid-network
    depends_on:
      - shopgrid-products-postgres

  shopgrid-orders-postgres:
    container_name: shopgrid-orders-postgres
    image: postgres:18-alpine
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_USER=mike
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=orders_db
    volumes:
      - shopgrid-orders-postgres-volume:/var/lib/postgresql/data
    networks:
      - shopgrid-network

  orders-service:
    build:
      context: .
      dockerfile: orders-service/Dockerfile
    container_name: orders-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - shopgrid-network
    depends_on:
      - shopgrid-orders-postgres

  shopgrid-users-postgres:
    container_name: shopgrid-users-postgres
    image: postgres:18-alpine
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=mike
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users_db
    volumes:
      - shopgrid-users-postgres-volume:/var/lib/postgresql/data
    networks:
      - shopgrid-network

  users-service:
    build:
      context: .
      dockerfile: users-service/Dockerfile
    container_name: users-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - shopgrid-network
    depends_on:
      - shopgrid-users-postgres

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_HOSTNAME=localhost # for local development
      - KC_HOSTNAME_PORT=8180
      - KC_DB_URL_HOST=keycloak-postgres
      - KC_DB_URL_DATABASE=keycloak_db
      - KC_DB_USERNAME=keycloak_user
      - KC_DB_PASSWORD=keycloak_password
      - KC_PROXY=edge
    ports:
      - "8180:8080"
    networks:
      - shopgrid-network
    depends_on:
      - keycloak-postgres
    command: start-dev

  keycloak-postgres:
    image: postgres:18-alpine
    container_name: keycloak-postgres
    environment:
      - POSTGRES_DB=keycloak_db
      - POSTGRES_USER=keycloak_user
      - POSTGRES_PASSWORD=keycloak_password
    volumes:
      - keycloak-postgres-volume:/var/lib/postgresql/data
    networks:
      - shopgrid-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    networks:
      - shopgrid-network
    depends_on:
      - users-service
      - products-service
      - orders-service

networks:
  shopgrid-network:
    driver: bridge

volumes:
  shopgrid-products-postgres-volume:
    driver: local
  shopgrid-orders-postgres-volume:
    driver: local
  shopgrid-users-postgres-volume:
    driver: local
  keycloak-postgres-volume:
    driver: local