services:
  shopgrid-products-postgres:
    extends:
      file: docker-compose.common.yaml
      service: base-shopgrid
    container_name: shopgrid-products-postgres
    image: postgres:18-alpine
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=${SHOPGRID_PRODUCTS_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${SHOPGRID_PRODUCTS_POSTGRES_PASSWORD}
      - POSTGRES_DB=products_db
    volumes:
      - shopgrid-products-postgres-volume:/var/lib/postgresql/data

  products-service:
    extends:
      file: docker-compose.common.yaml
      service: base-shopgrid-microservice
    build:
      context: .
      dockerfile: products-service/Dockerfile
    container_name: products-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shopgrid-products-postgres:5432/products_db
      - SPRING_DATASOURCE_USERNAME=${SHOPGRID_PRODUCTS_POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SHOPGRID_PRODUCTS_POSTGRES_PASSWORD}
      - OTEL_SERVICE_NAME=products-service
    depends_on:
      - shopgrid-products-postgres

  shopgrid-orders-postgres:
    extends:
      file: docker-compose.common.yaml
      service: base-shopgrid
    container_name: shopgrid-orders-postgres
    image: postgres:18-alpine
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_USER=${SHOPGRID_ORDERS_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${SHOPGRID_ORDERS_POSTGRES_PASSWORD}
      - POSTGRES_DB=orders_db
    volumes:
      - shopgrid-orders-postgres-volume:/var/lib/postgresql/data

  orders-service:
    extends:
      file: docker-compose.common.yaml
      service: base-shopgrid-microservice
    build:
      context: .
      dockerfile: orders-service/Dockerfile
    container_name: orders-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shopgrid-orders-postgres:5432/orders_db
      - SPRING_DATASOURCE_USERNAME=${SHOPGRID_ORDERS_POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SHOPGRID_ORDERS_POSTGRES_PASSWORD}
      - OTEL_SERVICE_NAME=orders-service
    depends_on:
      - shopgrid-orders-postgres

  shopgrid-users-postgres:
    extends:
      file: docker-compose.common.yaml
      service: base-shopgrid
    container_name: shopgrid-users-postgres
    image: postgres:18-alpine
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=${SHOPGRID_USERS_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${SHOPGRID_USERS_POSTGRES_PASSWORD}
      - POSTGRES_DB=users_db
    volumes:
      - shopgrid-users-postgres-volume:/var/lib/postgresql/data

  users-service:
    extends:
      file: docker-compose.common.yaml
      service: base-shopgrid-microservice
    build:
      context: .
      dockerfile: users-service/Dockerfile
    container_name: users-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shopgrid-users-postgres:5432/users_db
      - SPRING_DATASOURCE_USERNAME=${SHOPGRID_USERS_POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SHOPGRID_USERS_POSTGRES_PASSWORD}
      - KEYCLOAK_LOGIN_CLIENT-SECRET=${KEYCLOAK_FRONTEND_CLIENT_SECRET}
      - KEYCLOAK_ADMIN_CLIENT-SECRET=${KEYCLOAK_USERS_ADMIN_CLIENT_SECRET}
      - OTEL_SERVICE_NAME=users-service
    depends_on:
      - shopgrid-users-postgres

  keycloak:
    extends:
      file: docker-compose.common.yaml
      service: base-shopgrid
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_HOSTNAME=localhost # for local development
      - KC_HOSTNAME_PORT=8180
      - KC_DB_URL_HOST=keycloak-postgres
      - KC_DB_URL_DATABASE=keycloak_db
      - KC_DB_USERNAME=${KEYCLOAK_DB_USERNAME}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KC_PROXY=edge
    ports:
      - "8180:8080"
    depends_on:
      - keycloak-postgres
    command: start-dev

  keycloak-postgres:
    extends:
      file: docker-compose.common.yaml
      service: base-shopgrid
    image: postgres:18-alpine
    container_name: keycloak-postgres
    environment:
      - POSTGRES_DB=keycloak_db
      - POSTGRES_USER=${KEYCLOAK_DB_USERNAME}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak-postgres-volume:/var/lib/postgresql/data

  api-gateway:
    extends:
      file: docker-compose.common.yaml
      service: base-shopgrid-microservice
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - OTEL_SERVICE_NAME=api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - users-service
      - products-service
      - orders-service

  prometheus:
    extends:
      file: docker-compose.common.yaml
      service: base-shopgrid
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  loki:
    extends:
      file: docker-compose.common.yaml
      service: base-shopgrid
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    command:
      - '--config.file=/etc/loki/local-config.yaml'

  jaeger:
    extends:
      file: docker-compose.common.yaml
      service: base-shopgrid
    image: jaegertracing/all-in-one:1.53
    container_name: jaeger
    ports:
      - "9411:9411"
      - "16686:16686"
      - "4318:4318"

  grafana:
    extends:
      file: docker-compose.common.yaml
      service: base-shopgrid
    image: grafana/grafana:10.2.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - jaeger

  redis:
    extends:
      file: docker-compose.common.yaml
      service: base-shopgrid
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

networks:
  shopgrid-network:
    driver: bridge

volumes:
  shopgrid-products-postgres-volume:
    driver: local
  shopgrid-orders-postgres-volume:
    driver: local
  shopgrid-users-postgres-volume:
    driver: local
  keycloak-postgres-volume:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  loki-data:
    driver: local