server:
  port: 8090

spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://shopgrid-users-postgres:5432/users_db
    username: mike
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ShopGrid
          jwk-set-uri: http://keycloak:8080/realms/ShopGrid/protocol/openid-connect/certs
