server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: products-service
              uri: http://products-service:8088
              predicates:
                - Path=/api/v1/products/**
            - id: orders-service
              uri: http://orders-service:8089
              predicates:
                - Path=/api/v1/orders/**
            - id: users-service
              uri: http://users-service:8090
              predicates:
                - Path=/api/v1/users/**, /api/v1/auth/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ShopGrid
          jwk-set-uri: http://keycloak:8080/realms/ShopGrid/protocol/openid-connect/certs