server:
  port: 8089

spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:postgresql://shopgrid-orders-postgres:5432/orders_db
    username: mike
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create

app:
  services:
    products:
      url: http://products-service:8088
    users:
      url: http://users-service:8090