server:
  port: 8089

spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:postgresql://localhost:5439/orders_db
    username: mike
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create