apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
        - name: products-service
          image: shop-grid-products-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://shopgrid-products-postgres:5432/products_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: products-db-secret
                  key: SHOPGRID_PRODUCTS_POSTGRES_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: products-db-secret
                  key: SHOPGRID_PRODUCTS_POSTGRES_PASSWORD
            - name: OTEL_SERVICE_NAME
              value: products-service

---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app: products-service
  ports:
    - port: 8088
      targetPort: 8088