apiVersion: v1
kind: Secret
metadata:
  name: users-db-secret
type: Opaque
data:
  dPOSTGRES_USERNAME: bWlrZQ==
  SHOPGRID_USERS_POSTGRES_USERNAME: bWlrZQ==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  SHOPGRID_USERS_POSTGRES_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: products-db-secret
type: Opaque
data:
  POSTGRES_USERNAME: bWlrZQ==
  SHOPGRID_PRODUCTS_POSTGRES_USERNAME: bWlrZQ==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  SHOPGRID_PRODUCTS_POSTGRES_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: orders-db-secret
type: Opaque
data:
  POSTGRES_USERNAME: bWlrZQ==
  SHOPGRID_ORDERS_POSTGRES_USERNAME: bWlrZQ==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  SHOPGRID_ORDERS_POSTGRES_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
type: Opaque
data:
  KC_DB_USERNAME: a2V5Y2xvYWtfdXNlcg==
  KC_DB_PASSWORD: a2V5Y2xvYWtfcGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
type: Opaque
data:
  KEYCLOAK_ADMIN: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4=

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-frontend-secret
type: Opaque
data:
  KEYCLOAK_FRONTEND_CLIENT_SECRET: TnhScWR1OHVqa3ZqcVBaNFY2akVWWDhmcldyb05iQng=

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-users-admin-secret
type: Opaque
data:
  KEYCLOAK_USERS_ADMIN_CLIENT_SECRET: ZDIyM0kxMUlnVlpneEpXUkh3QmlUaFVmNzFCM1ZEZHc=
