server:
  port: 8088

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ShopGrid
          jwk-set-uri: http://keycloak:8080/realms/ShopGrid/protocol/openid-connect/certs