server:
  port: 8088

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.shopgrid:80/realms/ShopGrid
          jwk-set-uri: http://keycloak:8080/realms/ShopGrid/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}