server:
  port: 8088

spring:
  application:
    name: products-service
  datasource:
    url: jdbc:postgresql://localhost:5438/products_db
    username: mike
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create